googleAnalytics = "G-BBYXH07DGN"
baseURL = "https://nineties.github.io/topos-theory/"
languageCode = "ja-jp"
title = "Topos Theory"
theme = "hugo-book"
publishDir = "docs"
defaultContentLanguage = "ja"
enableGitInfo = true

[params]
BookTheme = 'light'
customCSS = ["static/custom.css"]
BookSection = '*'
BookRepo = 'https://github.com/nineties/topos-theory'
BookEditPath = 'blob/main'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
