baseURL = "https://nineties.github.io/topos-theory/"
languageCode = "ja-jp"
title = "Topos Theory"
theme = "hugo-book"
publishDir = "docs"
defaultContentLanguage = "ja"

[params]
customCSS = ["static/custom.css"]
BookSection = '*'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
